### ISSUE TITLE
As a player I want to produce some wares myself

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/parvenu#77]
# Terminology 
* _facs_ = production facilities (where the player produces wares) = 
* _warehouses_ = player "inventory" inside a city (into which the player's wares are produced)
* _bag_ = global player inventory (what he carries around into other cities)  

# Acceptance criteria
- [x] player can click to build production facilities
- [x] he can choose for which ware he builds a fac
- [x] building costs money
- [x] production facilities increase the corresponding ware quantity in the warehouse
- [x] production happens at the same time that cities consume and produce

### Restrictions
- [x] facs belong to cities
- [x] facs produce into a warehouse
- [x] facs of a specific ware can only be built if the city produces that ware

# Result
Parvenu is now an idle game.
